#repos:
#- repo: https://github.com/smit-darji/demotfsec.git
 # rev: v0.0.1 
  #hooks:
   # - id: tflint
repos:
-   repo: https://github.com/smit-darji/demotfsec.git
    rev: Master
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
