#repos:
#- repo: https://github.com/smit-darji/demotfsec.git
 # rev: v0.0.1 
  #hooks:
   # - id: tflint
repos:
-   repo: https://github.com/smit-darji/demotfsec.git
    rev: v0.0.1 
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/terraform-linters/tflint.git
    rev: v0.34.1
    hooks:
    -   id: tflint
        args: [--fix]
