#repos:
#- repo: https://github.com/smit-darji/demotfsec.git
 # rev: v0.0.1 
  #hooks:
   # - id: tflint
repos:
-   repo: https://github.com/smit-darji/demotfsec.git
    rev: v0.0.1 
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.10.0
    hooks:
    -   id: eslint
        args: [--fix]
