name: 'Check commit message style'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - Master
      - Devloper1
      - tester

jobs:
  steps:      
    - checkout      
    - run: ./scripts/commit-filter-check.sh

