name: 'Check commit message style'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - Master
      - Devloper1
      - tester

jobs:
  pull_request:
    name: Build and test
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'ci skip')"
