name: CodeNotary

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@Master
     
     - name: Verify
       uses: smit-darji/demotfsec@Master
