name: pre-commit

on:
  pull_request:
  push:
    branches: [Master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    
      - run: pip install pre-commit
      - run: pip install pre-commit-mirror-maker
      - uses: pre-commit/action@v2.0.3
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11
    - name: Terraform Format
      run: terraform fmt -check -diff -recursive
      
  # extract branch name on pull request
    - name: Print branch name Destination
      if: github.event_name == 'pull_request'
      run: echo "name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
