name: deploy
on:
  pull_request:
  push:
    branches: [Master]

jobs:
  build:
    name: pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: pip install virtualenv
    
