name: pre-commit

on:
  pull_request:
  push:
    branches: [Master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    
      - run: pip install pre-commit
      - run: pip install pre-commit-mirror-maker
      - uses: pre-commit/action@v2.0.3
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      

